### ISSUE TITLE
PfATP4

### ISSUE THREAD

**Issue by adw62** [NickWoods1/pcask1d#1]
Hiya,
tried to simulate the attached structure with this but it didnt work if you know why could you please let me know?

Thanks,
A
[PfATP4.txt](https://github.com/NickWoods1/pcask1d/files/3798258/PfATP4.txt)

**Comment by adw62** [comment]
Sorry think I worked it out, was a typo in my input!

**Comment by NickWoods1** [comment]
Glad you sorted your issue.
